#!/usr/bin/env bash
#MISE description="Build the app"

mkdir -p $APP_HOME/kestra-install
wget https://api.kestra.io/v1/versions/download -O $APP_HOME/kestra-install/kestra.zip
unzip $APP_HOME/kestra-install/kestra.zip -d $APP_HOME/kestra-install
rm -f $APP_HOME/kestra-install/kestra.zip

# The zip contains a single file, an executable jar without jar extension.
# We need to find this file and store it in the KESTRA_DIR variable.
# The problem is that the file name depends on the version, e.g. kestra-0.23.8
for file in $(ls $APP_HOME/kestra-install/*); do
    if [[ -f $file ]]; then
        KESTRA_EXEC="$file"
        break
    fi
done
ln -sf $KESTRA_EXEC $APP_HOME/kestra

export KESTRA_PLUGINS_PATH=$APP_HOME/kestra-install/plugins
mkdir -p $KESTRA_PLUGINS_PATH

# Install plugins
/opt/openjdk-bin-23.0.2_p7/bin/java -jar $APP_HOME/kestra plugins install io.kestra.storage:storage-minio:LATEST

# Install fdb
FDB_HOME=/home/bas/foundationdb

mkdir -p ${FDB_HOME}
cp foundationdb/* ${FDB_HOME}/

FDB_VERSION=7.3.68
wget -O ${FDB_HOME}/fdbserver https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/fdbserver.x86_64
wget -O ${FDB_HOME}/fdbmonitor https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/fdbmonitor.x86_64
wget -O ${FDB_HOME}/fdbcli https://github.com/apple/foundationdb/releases/download/${FDB_VERSION}/fdbcli.x86_64

chmod +x ${FDB_HOME}/fdbserver /home/bas/foundationdb/fdbmonitor /home/bas/foundationdb/fdbcli

echo PATH="\$PATH:$FDB_HOME" >> ~/.bashrc
echo FDB_HOME={$FDB_HOME} >> ~/.bashrc